version: '3.7'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  redis:
    image: "redis:alpine"

  db:
    image: "postgres"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname

  celery_worker:
    build: .
    command: celery -A app.worker.worker_config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
